### ISSUE TITLE
Atmega32u4 Compile Errors

### ISSUE THREAD

**Issue by Intechgreater** [Marthaarman/dmx-transceiver#5]
Greetings,

Is this library supposed to work with the atmega32u4 (Arduino Leonardo, Micro, etc)? Getting compile errors related to things not being defined/declared in scope.  I see how dmx_boards.h has some references to it since it's based on DMXSerial which does work with the mcu, but guessing there's more work involved to fully implement here? The reason I'm asking is for a project that requires sending/receiving DMX in the same sketch AND displaying info on an OLED screen via I2C. Any guidance would be appreciated.

**Comment by Intechgreater** [comment]
In the meantime I was able to get the project working by using the [SSD1306Ascii library](https://github.com/greiman/SSD1306Ascii) since I really only need basic text functionality.
It would still be nice to be able to run it on the 32u4 or other faster MCUs though.

**Comment by Lesateq** [comment]
Hello, I am curious which board you use. I have tried to get the the transceiver demo sketch working on an Arduino Nano. However, it seems to drop (a lot) of DMX input and most time it does not loop through DMX at all. It look like there is a performance issue since DMX needs quite some resources. DMXSerial works perfect, either Controller and Slave, but this library does not allow to do both in the same sketch.  I work with seperate MAX485 modules, so one setup for TX and another for RX. The reason I want to use the transceiver is that I want to change some DMX channel adresses from the RX side and send the translated channels to TX. Your comment / suggestions are really appreciated.

**Comment by Marthaarman** [comment]
> Greetings,
> 
> Is this library supposed to work with the atmega32u4 (Arduino Leonardo, Micro, etc)? Getting compile errors related to things not being defined/declared in scope. I see how dmx_boards.h has some references to it since it's based on DMXSerial which does work with the mcu, but guessing there's more work involved to fully implement here? The reason I'm asking is for a project that requires sending/receiving DMX in the same sketch AND displaying info on an OLED screen via I2C. Any guidance would be appreciated.

So far I built this code for an Arduino mini pro running on ATmega328P



> In the meantime I was able to get the project working by using the [SSD1306Ascii library](https://github.com/greiman/SSD1306Ascii) since I really only need basic text functionality. It would still be nice to be able to run it on the 32u4 or other faster MCUs though.

For now I do not have a motivation to build for the 32u4 but I'll check what I can do in the future

**Comment by Marthaarman** [comment]
> Hello, I am curious which board you use. I have tried to get the the transceiver demo sketch working on an Arduino Nano. However, it seems to drop (a lot) of DMX input and most time it does not loop through DMX at all. It look like there is a performance issue since DMX needs quite some resources. DMXSerial works perfect, either Controller and Slave, but this library does not allow to do both in the same sketch. I work with seperate MAX485 modules, so one setup for TX and another for RX. The reason I want to use the transceiver is that I want to change some DMX channel adresses from the RX side and send the translated channels to TX. Your comment / suggestions are really appreciated.

ATmega328P -> arduino mini pro
Check https://github.com/Marthaarman/dmx_interceptor_PCB for a pcb that integrates to max485 modules

**Comment by Lesateq** [comment]
Greetings as well! Thanks for your reply. Meanwhile I have stripped the sketch from the I/O I had implemented with a 4X4 keypad and a 1602 LCD display. Now the transceiver function works fine. I translate the DMX addresses using a lookup table. With Nano I guess you cannot add to much functionality besides the transceiver itselfs. Interesting, I ordered a 1306 OLED display two days before you answer... Of course I will try to get it working with the OLED.

**Comment by Intechgreater** [comment]
> Hello, I am curious which board you use. I have tried to get the the transceiver demo sketch working on an Arduino Nano. However, it seems to drop (a lot) of DMX input and most time it does not loop through DMX at all. It look like there is a performance issue since DMX needs quite some resources. DMXSerial works perfect, either Controller and Slave, but this library does not allow to do both in the same sketch. I work with seperate MAX485 modules, so one setup for TX and another for RX. The reason I want to use the transceiver is that I want to change some DMX channel adresses from the RX side and send the translated channels to TX. Your comment / suggestions are really appreciated.

Sorry for taking forever to respond! I also am using a Nano. One important thing I recall at the moment is to ensure adequate power is being supplied to all circuits/modules, along with the shared reference ground of course.

**Comment by Lesateq** [comment]
Hello Mart,

Thanks for your reply. The horsepower of the Nano is limited indeed. I have refined the code and I have removed I/O routines that I used for input on a numeric keypad and output on a LCD display. Next, I have used a lookup table for the DMX channel conversion. It seems to work well in this configuration.

I use the converter in the theatre where I work part-time. Now we can use a cheap and simple to operate DMX console:

(https://www.e-lektron.de/media/pdf/Bedienungsanleitungen/154066_C192A_operatingmanual_German.pdf

This is nice for ‘unattended’ business events where no engineer is on duty. Since this console works with burned in channels the conversion is necessary; it is not easy to change the DMX addresses of all fixtures in the theatre.

Have a nice day!

Kind regards,

Klaus Buenk

Van: AL-X ***@***.***>
Verzonden: maandag 22 april 2024 04:20
Aan: Marthaarman/dmx-transceiver ***@***.***>
CC: Klaus Buenk ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Marthaarman/dmx-transceiver] Atmega32u4 Compile Errors (Issue #5)


Hello, I am curious which board you use. I have tried to get the the transceiver demo sketch working on an Arduino Nano. However, it seems to drop (a lot) of DMX input and most time it does not loop through DMX at all. It look like there is a performance issue since DMX needs quite some resources. DMXSerial works perfect, either Controller and Slave, but this library does not allow to do both in the same sketch. I work with seperate MAX485 modules, so one setup for TX and another for RX. The reason I want to use the transceiver is that I want to change some DMX channel adresses from the RX side and send the translated channels to TX. Your comment / suggestions are really appreciated.

Sorry for taking forever to respond! I also am using a Nano. One important thing I recall at the moment is to ensure adequate power is being supplied to all circuits/modules, along with the shared reference ground of course.

**Comment by Marthaarman** [comment]
I suggest taking a look at https://github.com/Marthaarman/dmx_interceptor_PCB for a complete solution that you can build yourself, nicely on a PCB. 

I would suggest, however, not to use these modules in show-lighting since their update speed is not amazing and I will not guarantee their stability. 

Just for work-light these modules are a great solution. 

If you want these modules but are not able to make them yourselves let me know, then we'll see what I can do for you. You can contact me through my website. 

Currently I do not have time to refactor my code for another board such as the nano.
